version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/work
    working_dir: /home/jovyan/work
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlruns --default-artifact-root /mlruns
    volumes:
      - ../mlruns:/mlruns
